#!/usr/bin/env python3
# /// script
# requires-python = ">=3.10"
# dependencies = [
#   "PyYAML>=6.0",
# ]
# ///
"""Build the combined Legend of Mortal English mod package.

The script imports structured translation data from the sibling
LegendOfMortalOverLlm checkout, merges it with this repository's XUnity
dictionary, validates the generated files, writes reports, and creates an
installable zip from Mod/.
"""

from __future__ import annotations

import argparse
import collections
import csv
import json
import re
import subprocess
import zipfile
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import yaml


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_IMPORT_ROOT = ROOT.parent / "LegendOfMortalOverLlm"

MOD_DIR = ROOT / "Mod"
TEXT_DIR = MOD_DIR / "BepInEx" / "Translation" / "en" / "Text"
LOM_TRANSLATION = TEXT_DIR / "Translation zh-CN to en.txt"
AUTOGEN_TRANSLATION = TEXT_DIR / "_AutoGeneratedTranslations.txt"
STRINGTABLE_OUT = MOD_DIR / "Mods" / "English" / "StringTable.csv"
REPORTS_DIR = ROOT / "reports"
DIST_DIR = ROOT / "dist"
ZIP_OUT = DIST_DIR / "LegendOfMortal-English-combined.zip"

CHINESE_RE = re.compile(r"[\u3400-\u9fff]")
PLACEHOLDER_RE = re.compile(r"\{\d+\}")
TAG_RE = re.compile(r"</?\s*([A-Za-z][A-Za-z0-9]*)(?:\s*\\?=[^>]*)?>")
YAML_FRAGMENT_RE = re.compile(r"^\s*(-\s+raw:|raw:|result:|translated:|badtrans:)\b", re.I)
INSTRUCTION_LEAK_RE = re.compile(
    r"\b(as an ai|chatgpt|prompt|system message|translate the|translation:"
    r"|raw:|result:|badtrans|yaml|json object)\b",
    re.I,
)


@dataclass(frozen=True)
class Candidate:
    key: str
    value: str
    source: str
    path: str
    line: int
    ordinal: int


@dataclass(frozen=True)
class Rejection:
    key: str
    value: str
    source: str
    line: int
    reason: str


def read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8-sig")


def write_text(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8", newline="\n")


def split_unescaped_equals(line: str) -> tuple[str, str] | None:
    indexes: list[int] = []
    escaped = False
    for idx, char in enumerate(line):
        if char == "\\" and not escaped:
            escaped = True
            continue
        if char == "=" and not escaped:
            indexes.append(idx)
        escaped = False
    if len(indexes) != 1:
        return None
    idx = indexes[0]
    return line[:idx], line[idx + 1 :]


def unescape_xunity(text: str) -> str:
    return text.replace(r"\=", "=")


def escape_xunity(text: str) -> str:
    normalized = text.replace("\r\n", r"\n").replace("\r", r"\n").replace("\n", r"\n")
    normalized = normalized.replace(r"\=", "=")
    return normalized.replace("=", r"\=")


def linebreak_tokens(text: str) -> int:
    return text.count(r"\n") + text.count("\n")


def rich_tags(text: str) -> list[str]:
    return [match.group(0).replace(r"\=", "=").lower() for match in TAG_RE.finditer(text)]


def validate_translation(key: str, value: str) -> list[str]:
    reasons: list[str] = []
    key = key.strip()
    value = value.strip()

    if not key:
        reasons.append("empty_key")
    if not value:
        reasons.append("empty_translation")
    if YAML_FRAGMENT_RE.search(value):
        reasons.append("yaml_fragment")
    if INSTRUCTION_LEAK_RE.search(value):
        reasons.append("instruction_leak")
    if CHINESE_RE.search(value):
        reasons.append("remaining_chinese")
    if CHINESE_RE.search(key) and key == value:
        reasons.append("source_copy")
    if value.endswith("\\") and not value.endswith("\\\\"):
        reasons.append("dangling_escape")

    key_placeholders = sorted(PLACEHOLDER_RE.findall(key))
    value_placeholders = sorted(PLACEHOLDER_RE.findall(value))
    if key_placeholders != value_placeholders:
        reasons.append("placeholder_mismatch")

    key_tags = rich_tags(key)
    value_tags = rich_tags(value)
    if key_tags != value_tags:
        reasons.append("rich_tag_mismatch")

    if linebreak_tokens(key) != linebreak_tokens(value):
        reasons.append("newline_mismatch")

    return reasons


def parse_xunity_file(path: Path, source: str) -> tuple[list[Candidate], list[dict[str, Any]]]:
    candidates: list[Candidate] = []
    malformed: list[dict[str, Any]] = []
    ordinal = 0
    for line_no, line in enumerate(read_text(path).splitlines(), 1):
        stripped = line.strip()
        if not stripped or stripped.startswith("//") or stripped.startswith("#"):
            continue
        split = split_unescaped_equals(line)
        if split is None:
            malformed.append({"source": source, "line": line_no, "text": line[:180]})
            continue
        key, value = split
        ordinal += 1
        candidates.append(
            Candidate(
                key=unescape_xunity(key.strip()),
                value=unescape_xunity(value.strip()),
                source=source,
                path=str(path.relative_to(ROOT.parent)),
                line=line_no,
                ordinal=ordinal,
            )
        )
    return candidates, malformed


def load_yaml_list(path: Path) -> list[dict[str, Any]]:
    loaded = yaml.safe_load(read_text(path))
    if not isinstance(loaded, list):
        raise TypeError(f"{path} did not contain a YAML list")
    return [item for item in loaded if isinstance(item, dict)]


def parse_loose_scalar(value: str) -> str:
    value = value.strip()
    try:
        parsed = yaml.safe_load(value)
        if parsed is None:
            return ""
        return str(parsed)
    except yaml.YAMLError:
        if len(value) >= 2 and value[0] == value[-1] == '"':
            return value[1:-1]
        return value


def load_converted_stringtable(path: Path) -> list[dict[str, Any]]:
    try:
        return load_yaml_list(path)
    except (TypeError, yaml.YAMLError):
        items: list[dict[str, Any]] = []
        current: dict[str, Any] | None = None
        current_split: dict[str, Any] | None = None

        for line_no, line in enumerate(read_text(path).splitlines(), 1):
            stripped = line.strip()
            if not stripped:
                continue
            if stripped.startswith("- raw:"):
                current = {"raw": parse_loose_scalar(stripped.split(":", 1)[1]), "splits": []}
                items.append(current)
                current_split = None
            elif stripped.startswith("- split:") and current is not None:
                split_value = parse_loose_scalar(stripped.split(":", 1)[1])
                try:
                    split_value = int(split_value)
                except ValueError:
                    pass
                current_split = {"split": split_value}
                current["splits"].append(current_split)
            elif stripped.startswith("text:") and current_split is not None:
                current_split["text"] = parse_loose_scalar(stripped.split(":", 1)[1])
            elif "translated:" in stripped and current_split is not None:
                current_split["translated"] = parse_loose_scalar(stripped.split("translated:", 1)[1])
            elif stripped in {"splits:", "splits: []"}:
                continue
            else:
                raise ValueError(f"Cannot parse converted StringTable line {line_no}: {line[:180]}")

        return items


def first_existing(paths: list[Path]) -> Path:
    for path in paths:
        if path.exists():
            return path
    raise FileNotFoundError(", ".join(str(path) for path in paths))


def git_metadata(path: Path) -> dict[str, str]:
    def git(*args: str) -> str:
        return subprocess.check_output(
            ["git", *args],
            cwd=path,
            text=True,
            stderr=subprocess.DEVNULL,
        ).strip()

    try:
        return {
            "branch": git("branch", "--show-current"),
            "sha": git("rev-parse", "HEAD"),
            "short_sha": git("rev-parse", "--short", "HEAD"),
            "remote": git("remote", "get-url", "origin"),
        }
    except Exception:
        return {}


def yaml_candidates(path: Path, source: str, key_field: str = "raw", value_field: str = "result") -> list[Candidate]:
    candidates: list[Candidate] = []
    for idx, item in enumerate(load_yaml_list(path), 1):
        key = str(item.get(key_field) or "").strip()
        value = str(item.get(value_field) or "").strip()
        if not key and not value:
            continue
        candidates.append(
            Candidate(
                key=key,
                value=value,
                source=source,
                path=str(path.relative_to(ROOT.parent)),
                line=idx,
                ordinal=idx,
            )
        )
    return candidates


def glossary_candidates(path: Path) -> tuple[list[Candidate], dict[str, str]]:
    candidates: list[Candidate] = []
    glossary: dict[str, str] = {}
    for idx, item in enumerate(load_yaml_list(path), 1):
        result = str(item.get("result") or "").strip()
        if not result:
            continue
        keys = {
            str(item.get("raw") or "").strip(),
            str(item.get("rawSimplified") or "").strip(),
            str(item.get("rawTraditional") or "").strip(),
        }
        for key in sorted(k for k in keys if k):
            glossary[key] = result
            candidates.append(
                Candidate(
                    key=key,
                    value=result,
                    source="llm_glossary",
                    path=str(path.relative_to(ROOT.parent)),
                    line=idx,
                    ordinal=idx,
                )
            )
    return candidates, glossary


def candidate_score(candidate: Candidate, value_frequency: int, glossary: dict[str, str]) -> tuple[int, int, int, str]:
    key_len = len(candidate.key)
    source_base = {
        "lom_static": 100,
        "llm_manual": 98,
        "llm_auto": 94,
        "llm_glossary": 104,
    }.get(candidate.source, 90)
    score = source_base

    if key_len <= 12 and linebreak_tokens(candidate.key) == 0:
        if candidate.source == "lom_static":
            score += 25
        elif candidate.source == "llm_glossary":
            score += 35
        elif candidate.source.startswith("llm"):
            score -= 4

    if key_len >= 80 or linebreak_tokens(candidate.key) > 0:
        if candidate.source.startswith("llm"):
            score += 30
        if candidate.source == "lom_static":
            score -= 10

    expected = glossary.get(candidate.key)
    if expected:
        if candidate.value.casefold() == expected.casefold():
            score += 30
        elif expected.casefold() in candidate.value.casefold():
            score += 12

    score += min(value_frequency, 10)
    source_priority = {
        "llm_glossary": 4,
        "lom_static": 3,
        "llm_manual": 2,
        "llm_auto": 1,
    }.get(candidate.source, 0)
    return score, source_priority, candidate.ordinal, candidate.value


def choose_xunity_candidates(
    candidates: list[Candidate], glossary: dict[str, str]
) -> tuple[dict[str, Candidate], list[Rejection], dict[str, Any]]:
    valid_by_key: dict[str, list[Candidate]] = collections.defaultdict(list)
    rejections: list[Rejection] = []
    rejected_by_reason: collections.Counter[str] = collections.Counter()
    rejected_by_source: collections.Counter[str] = collections.Counter()

    for candidate in candidates:
        reasons = validate_translation(candidate.key, candidate.value)
        if reasons:
            for reason in reasons:
                rejected_by_reason[reason] += 1
            rejected_by_source[candidate.source] += 1
            rejections.append(
                Rejection(
                    key=candidate.key,
                    value=candidate.value,
                    source=candidate.source,
                    line=candidate.line,
                    reason=",".join(reasons),
                )
            )
            continue
        valid_by_key[candidate.key].append(candidate)

    chosen: dict[str, Candidate] = {}
    conflict_examples: list[dict[str, Any]] = []
    chosen_by_source: collections.Counter[str] = collections.Counter()
    conflict_count = 0

    for key, key_candidates in valid_by_key.items():
        value_counts = collections.Counter(candidate.value for candidate in key_candidates)
        distinct_values = sorted(value_counts)
        if len(distinct_values) > 1:
            conflict_count += 1
        winner = max(
            key_candidates,
            key=lambda candidate: candidate_score(candidate, value_counts[candidate.value], glossary),
        )
        chosen[key] = winner
        chosen_by_source[winner.source] += 1
        if len(distinct_values) > 1 and len(conflict_examples) < 30:
            conflict_examples.append(
                {
                    "key": key,
                    "chosen_source": winner.source,
                    "chosen": winner.value,
                    "alternatives": [
                        {
                            "source": candidate.source,
                            "value": candidate.value,
                            "line": candidate.line,
                        }
                        for candidate in key_candidates[:8]
                    ],
                }
            )

    stats = {
        "valid_keys": len(valid_by_key),
        "conflicts": conflict_count,
        "chosen_by_source": dict(sorted(chosen_by_source.items())),
        "rejected_by_reason": dict(sorted(rejected_by_reason.items())),
        "rejected_by_source": dict(sorted(rejected_by_source.items())),
        "conflict_examples": conflict_examples,
    }
    return chosen, rejections, stats


def write_xunity_dictionary(chosen: dict[str, Candidate]) -> dict[str, Any]:
    lines = [
        "////-------------Combined LoM_en + LegendOfMortalOverLlm authoritative dictionary////-------------",
        "////Generated by tools/build_combined_mod.py. Do not hand-edit generated ordering.////",
        "",
    ]
    for key in sorted(chosen):
        value = chosen[key].value
        lines.append(f"{escape_xunity(key)}={escape_xunity(value)}")
    write_text(LOM_TRANSLATION, "\n".join(lines) + "\n")
    write_text(AUTOGEN_TRANSLATION, "")
    return validate_xunity_output(LOM_TRANSLATION)


def validate_xunity_output(path: Path) -> dict[str, Any]:
    seen: set[str] = set()
    duplicate_keys: list[str] = []
    malformed: list[dict[str, Any]] = []
    remaining_chinese: list[dict[str, Any]] = []
    validation_failures: collections.Counter[str] = collections.Counter()
    entries = 0

    for line_no, line in enumerate(read_text(path).splitlines(), 1):
        stripped = line.strip()
        if not stripped or stripped.startswith("//") or stripped.startswith("#"):
            continue
        split = split_unescaped_equals(line)
        if split is None:
            malformed.append({"line": line_no, "text": line[:180]})
            continue
        key = unescape_xunity(split[0].strip())
        value = unescape_xunity(split[1].strip())
        entries += 1
        if key in seen:
            duplicate_keys.append(key)
        seen.add(key)
        if CHINESE_RE.search(value):
            remaining_chinese.append({"line": line_no, "key": key, "value": value})
        for reason in validate_translation(key, value):
            validation_failures[reason] += 1

    return {
        "entries": entries,
        "malformed_lines": malformed,
        "duplicate_keys": duplicate_keys[:50],
        "duplicate_key_count": len(duplicate_keys),
        "remaining_chinese_count": len(remaining_chinese),
        "remaining_chinese_examples": remaining_chinese[:25],
        "validation_failures": dict(sorted(validation_failures.items())),
    }


def validate_stringtable_value(source: str, translated: str) -> list[str]:
    reasons = validate_translation(source, translated)
    return [reason for reason in reasons if reason not in {"empty_key", "newline_mismatch"}]


def build_stringtable(import_root: Path) -> dict[str, Any]:
    raw_path = import_root / "Files" / "Raw" / "StringTable.csv"
    converted_path = first_existing(
        [
            import_root / "Files" / "Converted" / "StringTable.csv",
            import_root / "Files" / "Converted" / "StringTable.csv.yaml",
        ]
    )

    with raw_path.open(encoding="utf-8-sig", newline="") as handle:
        raw_rows = list(csv.reader(handle))
    converted = load_converted_stringtable(converted_path)

    if len(raw_rows) != len(converted):
        raise ValueError(f"StringTable row mismatch: raw={len(raw_rows)} converted={len(converted)}")

    output_rows: list[list[str]] = []
    invalid_rows: list[dict[str, Any]] = []
    alignment_mismatches: list[dict[str, Any]] = []
    translated_count = 0
    fallback_count = 0
    rejected_by_reason: collections.Counter[str] = collections.Counter()

    for idx, (raw_row, converted_item) in enumerate(zip(raw_rows, converted, strict=True), 1):
        if len(raw_row) != 2:
            raise ValueError(f"Raw StringTable row {idx} did not contain two columns")
        row_key, source_text = raw_row
        converted_raw = str(converted_item.get("raw") or "")
        if converted_raw and not converted_raw.startswith(f"{row_key},"):
            alignment_mismatches.append(
                {"row": idx, "raw_key": row_key, "converted_raw": converted_raw[:180]}
            )

        splits = converted_item.get("splits") or []
        translated = ""
        if len(splits) == 1 and isinstance(splits[0], dict):
            translated = str(splits[0].get("translated") or "").strip()
        elif len(splits) > 1:
            translated = "".join(str(split.get("translated") or "") for split in splits if isinstance(split, dict)).strip()

        if translated:
            reasons = validate_stringtable_value(source_text, translated)
            if reasons:
                fallback_count += 1
                for reason in reasons:
                    rejected_by_reason[reason] += 1
                invalid_rows.append(
                    {
                        "row": idx,
                        "key": row_key,
                        "source": source_text,
                        "candidate": translated,
                        "reason": ",".join(reasons),
                    }
                )
                translated = source_text
            else:
                translated_count += 1
        else:
            translated = source_text
            if source_text:
                fallback_count += 1

        output_rows.append([row_key, translated])

    STRINGTABLE_OUT.parent.mkdir(parents=True, exist_ok=True)
    with STRINGTABLE_OUT.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.writer(handle, lineterminator="\n")
        writer.writerows(output_rows)

    validation = validate_stringtable(raw_path)
    validation.update(
        {
            "raw_path": str(raw_path.relative_to(import_root)),
            "converted_path": str(converted_path.relative_to(import_root)),
            "source_rows": len(raw_rows),
            "converted_rows": len(converted),
            "translated_rows": translated_count,
            "fallback_rows": fallback_count,
            "invalid_candidate_rows": len(invalid_rows),
            "invalid_candidate_examples": invalid_rows[:25],
            "rejected_by_reason": dict(sorted(rejected_by_reason.items())),
            "alignment_mismatch_count": len(alignment_mismatches),
            "alignment_mismatch_examples": alignment_mismatches[:25],
        }
    )
    return validation


def validate_stringtable(raw_path: Path) -> dict[str, Any]:
    with raw_path.open(encoding="utf-8-sig", newline="") as handle:
        raw_rows = list(csv.reader(handle))
    with STRINGTABLE_OUT.open(encoding="utf-8", newline="") as handle:
        out_rows = list(csv.reader(handle))

    remaining_chinese = []
    yaml_fragments = []
    for idx, row in enumerate(out_rows, 1):
        if len(row) != 2:
            yaml_fragments.append({"row": idx, "problem": "column_count", "value": row[:4]})
            continue
        value = row[1]
        if CHINESE_RE.search(value):
            remaining_chinese.append({"row": idx, "key": row[0], "value": value[:180]})
        if YAML_FRAGMENT_RE.search(value):
            yaml_fragments.append({"row": idx, "key": row[0], "value": value[:180]})

    return {
        "output_rows": len(out_rows),
        "row_count_matches_raw": len(raw_rows) == len(out_rows),
        "remaining_chinese_count": len(remaining_chinese),
        "remaining_chinese_examples": remaining_chinese[:25],
        "yaml_fragment_count": len(yaml_fragments),
        "yaml_fragment_examples": yaml_fragments[:25],
    }


def quality_comparison(candidates: list[Candidate], chosen: dict[str, Candidate]) -> dict[str, Any]:
    by_key: dict[str, list[Candidate]] = collections.defaultdict(list)
    for candidate in candidates:
        if not validate_translation(candidate.key, candidate.value):
            by_key[candidate.key].append(candidate)

    categories: dict[str, Any] = {
        "short_ui": {"predicate": lambda key: len(key) <= 12 and linebreak_tokens(key) == 0},
        "system_combat": {
            "predicate": lambda key: any(
                term in key
                for term in (
                    "攻擊",
                    "攻击",
                    "防禦",
                    "防御",
                    "技能",
                    "狀態",
                    "状态",
                    "屬性",
                    "属性",
                    "回合",
                    "氣力",
                    "气力",
                )
            )
        },
        "names_terms": {"predicate": lambda key: len(key) <= 8 and CHINESE_RE.search(key) is not None},
        "long_story": {"predicate": lambda key: len(key) >= 80 or linebreak_tokens(key) > 0},
    }

    output: dict[str, Any] = {}
    for name, item in categories.items():
        predicate = item["predicate"]
        keys = [
            key
            for key, key_candidates in by_key.items()
            if predicate(key) and len({candidate.value for candidate in key_candidates}) > 1
        ]
        chosen_sources = collections.Counter(chosen[key].source for key in keys if key in chosen)
        examples = []
        for key in keys[:8]:
            examples.append(
                {
                    "key": key,
                    "chosen_source": chosen[key].source if key in chosen else None,
                    "chosen": chosen[key].value if key in chosen else None,
                    "candidate_count": len(by_key[key]),
                }
            )
        output[name] = {
            "conflicting_keys": len(keys),
            "chosen_sources": dict(sorted(chosen_sources.items())),
            "examples": examples,
        }
    return output


def validate_package() -> dict[str, Any]:
    required = {
        "BepInEx/",
        "Mods/English/StringTable.csv",
        ".doorstop_version",
        "doorstop_config.ini",
        "winhttp.dll",
    }
    config_path = "BepInEx/config/AutoTranslatorConfig.ini"
    names = set()
    with zipfile.ZipFile(ZIP_OUT) as archive:
        names = set(archive.namelist())
        try:
            config_text = archive.read(config_path).decode("utf-8-sig")
        except KeyError:
            config_text = ""

    has_bepinex = any(name.startswith("BepInEx/") for name in names)
    has_textures = any(name.startswith("BepInEx/Translation/en/Texture/") and name.endswith(".png") for name in names)
    missing = sorted(item for item in required if item != "BepInEx/" and item not in names)
    if not has_bepinex:
        missing.append("BepInEx/")
    if config_path not in names:
        missing.append(config_path)

    config_checks = {
        "Language=en": "Language=en" in config_text,
        "FromLanguage=zh-CN": "FromLanguage=zh-CN" in config_text,
        "EnableTextureTranslation=True": "EnableTextureTranslation=True" in config_text,
    }
    return {
        "zip": str(ZIP_OUT.relative_to(ROOT)),
        "file_count": len(names),
        "missing_required": missing,
        "has_textures": has_textures,
        "config_checks": config_checks,
    }


def build_zip() -> dict[str, Any]:
    DIST_DIR.mkdir(parents=True, exist_ok=True)
    if ZIP_OUT.exists():
        ZIP_OUT.unlink()
    with zipfile.ZipFile(ZIP_OUT, "w", compression=zipfile.ZIP_DEFLATED, compresslevel=9) as archive:
        for path in sorted(MOD_DIR.rglob("*")):
            if path.is_file():
                archive.write(path, path.relative_to(MOD_DIR).as_posix())
    return validate_package()


def write_reports(report: dict[str, Any]) -> None:
    REPORTS_DIR.mkdir(parents=True, exist_ok=True)
    json_path = REPORTS_DIR / "merge_report.json"
    md_path = REPORTS_DIR / "merge_report.md"
    write_text(json_path, json.dumps(report, ensure_ascii=False, indent=2) + "\n")

    xunity = report["xunity"]
    stringtable = report["stringtable"]
    package = report["package"]
    source_git = report.get("source_git", {})
    import_git = source_git.get("import", {})
    base_git = source_git.get("base", {})
    lines = [
        "# Combined Legend of Mortal English Mod Merge Report",
        "",
        "Generated by `tools/build_combined_mod.py`.",
        "",
        "## Source Revisions",
        "",
        f"- Base checkout: `{base_git.get('branch', 'unknown')}` @ `{base_git.get('short_sha', 'unknown')}`",
        f"- Import checkout: `{import_git.get('branch', 'unknown')}` @ `{import_git.get('short_sha', 'unknown')}`",
        f"- Import remote: `{import_git.get('remote', 'unknown')}`",
        "",
        "## Source Policy",
        "",
        "- Base repository: `LoM_en` BepInEx/XUnity package, config, textures, loader files, and UI helper files.",
        "- Imported translation source: `LegendOfMortalOverLlm/Files` structured StringTable, autotranslator dictionary, manual translations, and glossary.",
        "- Deterministic selection: LoM wins short UI and player-tested labels; LLM wins long narrative/story text when validation passes; glossary terms win exact short-term matches.",
        "- No LLM adjudication or API key was used in this run.",
        "",
        "## XUnity Dictionary",
        "",
        f"- Final entries: {xunity['validation']['entries']}",
        f"- Chosen by source: `{json.dumps(xunity['selection']['chosen_by_source'], ensure_ascii=False)}`",
        f"- Conflicting valid keys: {xunity['selection']['conflicts']}",
        f"- Rejected candidates by reason: `{json.dumps(xunity['selection']['rejected_by_reason'], ensure_ascii=False)}`",
        f"- Malformed source lines: {len(xunity['malformed_source_lines'])}",
        f"- Duplicate keys in final output: {xunity['validation']['duplicate_key_count']}",
        f"- Remaining Chinese in final English values: {xunity['validation']['remaining_chinese_count']}",
        f"- Final validation failures: `{json.dumps(xunity['validation']['validation_failures'], ensure_ascii=False)}`",
        "",
        "## StringTable.csv",
        "",
        f"- Raw rows: {stringtable['source_rows']}",
        f"- Converted rows: {stringtable['converted_rows']}",
        f"- Converted source path: `{stringtable['converted_path']}`",
        f"- Output rows: {stringtable['output_rows']}",
        f"- Row count matches raw: {stringtable['row_count_matches_raw']}",
        f"- Translated rows: {stringtable['translated_rows']}",
        f"- Fallback rows: {stringtable['fallback_rows']}",
        f"- Remaining Chinese in values: {stringtable['remaining_chinese_count']}",
        f"- YAML fragments in output: {stringtable['yaml_fragment_count']}",
        "",
        "## Package",
        "",
        f"- Zip: `{package['zip']}`",
        f"- Zip file count: {package['file_count']}",
        f"- Missing required paths: `{json.dumps(package['missing_required'], ensure_ascii=False)}`",
        f"- Textures included: {package['has_textures']}",
        f"- Config checks: `{json.dumps(package['config_checks'], ensure_ascii=False)}`",
        "",
        "## Stratified Conflict Check",
        "",
    ]
    for name, data in report["quality_comparison"].items():
        lines.extend(
            [
                f"### {name}",
                "",
                f"- Conflicting keys sampled: {data['conflicting_keys']}",
                f"- Chosen sources: `{json.dumps(data['chosen_sources'], ensure_ascii=False)}`",
                "",
            ]
        )
    lines.extend(
        [
            "## Remaining Risk",
            "",
            "- Static validation cannot prove every line is idiomatic in-game.",
            "- The game was not launched; package/static validation is the acceptance gate for this run.",
            "- Any rejected imported candidate remains visible in `reports/merge_report.json` for follow-up review.",
            "",
        ]
    )
    write_text(md_path, "\n".join(lines))


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--import-root",
        type=Path,
        default=DEFAULT_IMPORT_ROOT,
        help="Path to the LegendOfMortalOverLlm checkout.",
    )
    args = parser.parse_args()
    import_root = args.import_root.resolve()
    if not import_root.exists():
        raise FileNotFoundError(import_root)

    llm_auto_path = import_root / "Files" / "Autotranslator" / "_AutoGeneratedTranslations.txt"
    llm_manual_path = import_root / "Files" / "ManualTranslations.yaml"
    glossary_path = import_root / "Files" / "Glossary.yaml"

    lom_candidates, lom_malformed = parse_xunity_file(LOM_TRANSLATION, "lom_static")
    llm_auto_candidates, llm_auto_malformed = parse_xunity_file(llm_auto_path, "llm_auto")
    llm_manual_candidates = yaml_candidates(llm_manual_path, "llm_manual")
    glossary_entry_candidates, glossary = glossary_candidates(glossary_path)

    all_candidates = lom_candidates + llm_auto_candidates + llm_manual_candidates + glossary_entry_candidates
    chosen, rejections, selection_stats = choose_xunity_candidates(all_candidates, glossary)
    xunity_validation = write_xunity_dictionary(chosen)
    stringtable_validation = build_stringtable(import_root)
    package_validation = build_zip()

    report = {
        "source_roots": {
            "base": ROOT.name,
            "import": import_root.name,
        },
        "source_git": {
            "base": git_metadata(ROOT),
            "import": git_metadata(import_root),
        },
        "source_entries": {
            "lom_static": len(lom_candidates),
            "llm_auto": len(llm_auto_candidates),
            "llm_manual": len(llm_manual_candidates),
            "llm_glossary": len(glossary_entry_candidates),
        },
        "xunity": {
            "malformed_source_lines": lom_malformed + llm_auto_malformed,
            "selection": selection_stats,
            "rejection_examples": [
                {
                    "source": rejection.source,
                    "line": rejection.line,
                    "reason": rejection.reason,
                    "key": rejection.key[:180],
                    "value": rejection.value[:180],
                }
                for rejection in rejections[:200]
            ],
            "validation": xunity_validation,
        },
        "stringtable": stringtable_validation,
        "quality_comparison": quality_comparison(all_candidates, chosen),
        "package": package_validation,
    }
    write_reports(report)

    failures = []
    if xunity_validation["malformed_lines"]:
        failures.append("final XUnity dictionary has malformed lines")
    if xunity_validation["duplicate_key_count"]:
        failures.append("final XUnity dictionary has duplicate keys")
    if xunity_validation["validation_failures"]:
        failures.append("final XUnity dictionary failed validation")
    if not stringtable_validation["row_count_matches_raw"]:
        failures.append("StringTable row count mismatch")
    if stringtable_validation["yaml_fragment_count"]:
        failures.append("StringTable contains YAML fragments")
    if package_validation["missing_required"]:
        failures.append("package is missing required paths")
    if not all(package_validation["config_checks"].values()):
        failures.append("AutoTranslator config checks failed")

    if failures:
        for failure in failures:
            print(f"ERROR: {failure}")
        print(f"See {REPORTS_DIR / 'merge_report.json'}")
        return 1

    print(f"Wrote {LOM_TRANSLATION.relative_to(ROOT)}")
    print(f"Wrote {STRINGTABLE_OUT.relative_to(ROOT)}")
    print(f"Wrote {REPORTS_DIR.relative_to(ROOT) / 'merge_report.md'}")
    print(f"Wrote {ZIP_OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
